spring:
  #  datasource:
  #    url: jdbc:h2:tcp://localhost/~/brunch
  #    username: sa
  #    password:
  #    driver-class-name: org.h2.Driver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.ctuwa40yk0uo.ap-northeast-2.rds.amazonaws.com:3306/brunch?serverTimezone=Asia/Seoul
    username: root
    password: 1234qwer

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false
    defer-datasource-initialization: true

  #ouath2 추가 시작
  security:
    oauth2:
      client:
        registration:
          kakao:
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            client-id: 12560c5f0bc4d7c99650d6856f34c73e
            client-secret: r6yblqdKVUrHIGYTZVnS5inUK4d98Ja8
            client-authentication-method: client_secret_post
            client-name: kakao
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  #추가 끝
logging:
  level:
    org.hibernate:
      SQL: debug
